# Use Go's official image as a base
FROM golang:1.21-alpine

# Set working directory inside the container
WORKDIR /app

# Copy the miner node Go code into the container
COPY miner/main.go .

# Set up Go modules
RUN go mod init blockchain
RUN go mod tidy

# Build the miner node binary
RUN go build -o miner_node main.go

# Run the miner node binary when the container starts
CMD ["./miner_node"]
