version: '3.7'

services:
  user-node-1:
    build: ./user
    ports:
      - "8081:8081"
    networks:
      - blockchain-net

  user-node-2:
    build: ./user
    ports:
      - "8082:8082"
    networks:
      - blockchain-net

  user-node-3:
    build: ./user
    ports:
      - "8083:8083"
    networks:
      - blockchain-net

  user-node-4:
    build: ./user
    ports:
      - "8084:8084"
    networks:
      - blockchain-net

  miner-node-1:
    build: ./miner
    ports:
      - "8085:8085"
    networks:
      - blockchain-net

  miner-node-2:
    build: ./miner
    ports:
      - "8086:8086"
    networks:
      - blockchain-net

  miner-node-3:
    build: ./miner
    ports:
      - "8087:8087"
    networks:
      - blockchain-net

networks:
  blockchain-net:
    driver: bridge
