version: '3'
services:
  miner-node-1:
    build:
      context: .
      dockerfile: Dockerfile.miner
    ports:
      - "8081:8081"
    networks:
      - blockchain-net
    environment:
      - NODE_ID=miner-node-1

  miner-node-2:
    build:
      context: .
      dockerfile: Dockerfile.miner
    ports:
      - "8082:8081"
    networks:
      - blockchain-net
    environment:
      - NODE_ID=miner-node-2

  miner-node-3:
    build:
      context: .
      dockerfile: Dockerfile.miner
    ports:
      - "8083:8081"
    networks:
      - blockchain-net
    environment:
      - NODE_ID=miner-node-3

  user-node-1:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8084:8080"  # Adjusted internal/external port to match your Go code
    networks:
      - blockchain-net
    environment:
      - NODE_ID=user-node-1

  user-node-2:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8085:8080"  # Adjusted internal/external port to match your Go code
    networks:
      - blockchain-net
    environment:
      - NODE_ID=user-node-2

  user-node-3:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8086:8080"  # Adjusted internal/external port to match your Go code
    networks:
      - blockchain-net
    environment:
      - NODE_ID=user-node-3

  user-node-4:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8087:8080"  # Adjusted internal/external port to match your Go code
    networks:
      - blockchain-net
    environment:
      - NODE_ID=user-node-4

networks:
  blockchain-net:
    driver: bridge
