version: '3.8'

services:
  miner-node:
    build:
      context: .
      dockerfile: Dockerfile.miner
    container_name: miner-node
    networks:
      - blockchain-net
    ports:
      - "8081:8081"  # Expose miner port to the outside
    environment:
      - MINER_PORT=8081  # Set miner port, though this is mainly internal
    restart: unless-stopped

  user-node:
    build:
      context: .
      dockerfile: Dockerfile.user
    container_name: user-node
    networks:
      - blockchain-net
    environment:
      - MINER_ADDRESS=miner-node:8081  # Use miner container's hostname and port
    restart: unless-stopped

networks:
  blockchain-net:
    driver: bridge
