# Use Go's official image as a base
FROM golang:1.21-alpine

# Set working directory inside the container
WORKDIR /app

# Copy the user node Go code into the container
COPY user/main.go .

# Set up Go modules
RUN go mod init blockchain
RUN go mod tidy

# Build the user node binary
RUN go build -o user_node main.go

# Run the user node binary when the container starts
CMD ["./user_node"]
